"""
schema_validator.py

Schema Validator for ATS Schema Engine.

Responsibilities
----------------
- Validate Master Schema generated by schema_generator.py.
- Ensure all structural rules defined in the ATS architecture are satisfied:
    - required top-level fields
    - sheet structure validity
    - column definitions correctness
    - row_start validity
    - blocks validity
- Raise SchemaValidationError with explicit messages on failure.
- Return validated schema (unchanged) on success.

This module does NOT write files and does NOT modify the schema.
It is a pure validation layer used by the Schema Engine pipeline.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Dict, List

logger = logging.getLogger(__name__)


# -----------------------------------------------------------------------------
# Exceptions
# -----------------------------------------------------------------------------


class SchemaValidationError(Exception):
    """Raised when schema validation fails."""


# -----------------------------------------------------------------------------
# Validator Class
# -----------------------------------------------------------------------------


class SchemaValidator:
    """
    Validate Master Schema structure according to ATS schema rules.

    Usage:
    ------
        validator = SchemaValidator()
        validator.validate(schema_dict)
    """

    VALID_TYPES = {"number", "string", "date", "bool"}

    # -------------------------------------------------------------------------
    # Public API
    # -------------------------------------------------------------------------

    def validate(self, schema: Dict[str, Any]) -> Dict[str, Any]:
        """
        Validate Master Schema structure.
        Returns schema unchanged if valid.
        Raises SchemaValidationError if invalid.
        """
        logger.info("Validating Master Schema")

        self._validate_top_level(schema)

        sheets = schema.get("sheets", {})
        if not isinstance(sheets, dict):
            raise SchemaValidationError("'sheets' must be a dict")

        for sheet_name, sheet_def in sheets.items():
            self._validate_sheet(sheet_name, sheet_def)

        logger.info("Schema validation complete — VALID")
        return schema

    # -------------------------------------------------------------------------
    # Top-level structure
    # -------------------------------------------------------------------------

    def _validate_top_level(self, schema: Dict[str, Any]) -> None:
        """
        Validate root-level required fields.
        """
        if "project" not in schema:
            raise SchemaValidationError("Missing required field: 'project'")
        if "version" not in schema:
            raise SchemaValidationError("Missing required field: 'version'")
        if "sheets" not in schema:
            raise SchemaValidationError("Missing required field: 'sheets'")

        if not isinstance(schema["project"], str):
            raise SchemaValidationError("'project' must be a string")

        if not isinstance(schema["version"], str):
            raise SchemaValidationError("'version' must be a string")

    # -------------------------------------------------------------------------
    # Sheet validation
    # -------------------------------------------------------------------------

    def _validate_sheet(self, name: str, sheet: Dict[str, Any]) -> None:
        """
        Validate a single sheet structure.
        """
        if not isinstance(sheet, dict):
            raise SchemaValidationError(f"Sheet '{name}' must be a dict")

        required = ["name", "type", "row_start", "columns"]
        for key in required:
            if key not in sheet:
                raise SchemaValidationError(
                    f"Sheet '{name}' missing required field '{key}'"
                )

        # name
        if sheet["name"] != name:
            raise SchemaValidationError(
                f"Sheet name mismatch: key '{name}' != sheet['name'] '{sheet['name']}'"
            )

        # type
        if not isinstance(sheet["type"], str):
            raise SchemaValidationError(
                f"Sheet '{name}' field 'type' must be a string"
            )

        # row_start
        row_start = sheet["row_start"]
        if not isinstance(row_start, int) or row_start < 1:
            raise SchemaValidationError(
                f"Sheet '{name}': 'row_start' must be a positive integer"
            )

        # columns
        columns = sheet["columns"]
        if not isinstance(columns, list):
            raise SchemaValidationError(
                f"Sheet '{name}': 'columns' must be a list"
            )

        self._validate_columns(name, columns)

        # blocks (optional)
        if "blocks" in sheet:
            self._validate_blocks(name, sheet["blocks"])

    # -------------------------------------------------------------------------
    # Column validation
    # -------------------------------------------------------------------------

    def _validate_columns(self, sheet_name: str, columns: List[Dict[str, Any]]) -> None:
        """
        Validate column definitions:
            - col (A/B/C…)
            - name
            - python_key
            - type
        Check for:
            - duplicates
            - invalid type
        """
        seen_keys = set()
        seen_cols = set()

        for idx, col in enumerate(columns):
            if not isinstance(col, dict):
                raise SchemaValidationError(
                    f"Sheet '{sheet_name}': column #{idx} is not a dict"
                )

            # Required fields
            required = ["col", "name", "python_key", "type"]
            for key in required:
                if key not in col:
                    raise SchemaValidationError(
                        f"Sheet '{sheet_name}' column #{idx} missing required '{key}'"
                    )

            # col letter
            col_letter = col["col"]
            if not isinstance(col_letter, str) or not col_letter.strip():
                raise SchemaValidationError(
                    f"Sheet '{sheet_name}' column #{idx}: invalid 'col'"
                )
            if col_letter in seen_cols:
                raise SchemaValidationError(
                    f"Sheet '{sheet_name}' has duplicate col letter '{col_letter}'"
                )
            seen_cols.add(col_letter)

            # python_key
            python_key = col["python_key"]
            if not isinstance(python_key, str):
                raise SchemaValidationError(
                    f"Sheet '{sheet_name}' column #{col_letter}: python_key must be a string"
                )
            if python_key in seen_keys:
                raise SchemaValidationError(
                    f"Sheet '{sheet_name}' has duplicate python_key '{python_key}'"
                )
            seen_keys.add(python_key)

            # type
            col_type = col["type"]
            if col_type not in self.VALID_TYPES:
                raise SchemaValidationError(
                    f"Sheet '{sheet_name}' column '{python_key}': invalid type '{col_type}'"
                )

    # -------------------------------------------------------------------------
    # Blocks validation
    # -------------------------------------------------------------------------

    def _validate_blocks(self, sheet_name: str, blocks: Any) -> None:
        """
        Validate optional blocks field:
        blocks = {
            "Summary": { "total_equity": "B4", "cash": "B5", ... }
        }
        """
        if not isinstance(blocks, dict):
            raise SchemaValidationError(
                f"Sheet '{sheet_name}': 'blocks' must be a dict"
            )

        for block_name, mapping in blocks.items():
            if not isinstance(mapping, dict):
                raise SchemaValidationError(
                    f"Sheet '{sheet_name}' block '{block_name}' must be a dict"
                )
            for key, cell in mapping.items():
                if not isinstance(cell, str) or not cell.strip():
                    raise SchemaValidationError(
                        f"Sheet '{sheet_name}' block '{block_name}': invalid cell '{cell}'"
                    )
                # Very basic A1 validation (optional)
                if not self._looks_like_a1(cell):
                    raise SchemaValidationError(
                        f"Sheet '{sheet_name}' block '{block_name}': invalid A1 reference '{cell}'"
                    )

    @staticmethod
    def _looks_like_a1(cell: str) -> bool:
        """
        Simple A1 format validator (e.g., B4, AA10).
        """
        import re

        return bool(re.fullmatch(r"[A-Za-z]+[0-9]+", cell))
